### ISSUE TITLE
Secret VccIO Pins

### ISSUE THREAD

**Issue by peterzieba** [bkw777/ATF150x_uDEV#1]
Hi,

Since you're making a dev board for the 44-pin TQFP, I figured I'd mention a little tidbit that I came across:

The bigger parts (like the ATF1504AS and the ATF1508AS in >44pin packages) have separate lines for VccIO and VccCore and so can technically be run at 3.3V IO as mentioned in their datasheets.

What isn't mentioned in the datasheet is that this is likely possible all the same for the 44-pin parts.
On the smaller 44-pin parts they simply have 4 Vcc pins in the datasheet, however, if you hit them with a voltmeter, you'll find that two are connected to eachother, and the other two are connected to eachother. I'm pretty sure the 44-pin devices are capable of running independent VccCore at 5V and VccIO at 3.3V just as well.

I have yet to test this in a circuit, but between this mystery programming adapter PDF and the ohmmeter checks, it seems likely that this would work:
http://matthieu.benoit.free.fr/all03/adp/HiLo_ADP-ATF1504.PDF

I intend to make a board that tests this theory at some point.
Cheers

**Comment by bkw777** [comment]
Yeah I saw some posts about that and verified with a dmm the same way.

In another [project](https://github.com/bkw777/REX_ATF) I made a symbol that labels pins 9 & 29 as VCCA and  17 & 41 as VCCB, just because since they don't have continuity in the chip, I want any schematic to show, and any user to know, that these are two different nets that must both be supplied, even if they must both be supplied with the same thing.

But I haven't yet tested to see if they actually function as VCC & VCCIO.

If it checks out and behaves as VCCIO and doesn't cause any apparent problem I'll update the board to break those out.

**Comment by bkw777** [comment]
AHA!
The official manual for ATF15xx-DK3-U has a schematic that labels tqfp44 pins 9 & 29 as VCCIO and 17 & 41 as VCCINT !

https://www.microchip.com/en-us/development-tool/atf15xx-dk3-u

https://ww1.microchip.com/downloads/aemDocuments/documents/OTH/ProductDocuments/UserGuides/Atmel-8961-CPLD-ATF15xx-DK3-U-Development-Kit-UserGuide.pdf


![ATF15xx-DK3-U p16](https://github.com/user-attachments/assets/83f71de4-8501-453d-8e4a-3c73161dbef0)

**Comment by bkw777** [comment]
d96517f0
